-- دیتابیس پنل مدیریت قرارگاه رسانه‌ای
-- این فایل را کامل در Supabase > SQL Editor اجرا کنید.

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'اطلاعیه',
  body text not null,
  media_url text,
  media_type text check (media_type in ('image','video') or media_type is null),
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists posts_published_idx on public.posts(published);

alter table public.admin_users enable row level security;
alter table public.posts enable row level security;

-- فقط مدیرانی که در admin_users ثبت شده‌اند اجازه مدیریت دارند.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users where id = auth.uid());
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- سیاست‌های posts
 drop policy if exists "public can read published posts" on public.posts;
create policy "public can read published posts"
on public.posts for select
using (published = true or public.is_admin());

 drop policy if exists "admins can insert posts" on public.posts;
create policy "admins can insert posts"
on public.posts for insert to authenticated
with check (public.is_admin());

 drop policy if exists "admins can update posts" on public.posts;
create policy "admins can update posts"
on public.posts for update to authenticated
using (public.is_admin()) with check (public.is_admin());

 drop policy if exists "admins can delete posts" on public.posts;
create policy "admins can delete posts"
on public.posts for delete to authenticated
using (public.is_admin());

-- Bucket عمومی برای نمایش رسانه‌ها؛ خود آپلود/حذف فقط برای مدیران مجاز است.
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;

 drop policy if exists "public can view media" on storage.objects;
create policy "public can view media"
on storage.objects for select
using (bucket_id = 'media');

 drop policy if exists "admins can upload media" on storage.objects;
create policy "admins can upload media"
on storage.objects for insert to authenticated
with check (bucket_id = 'media' and public.is_admin());

 drop policy if exists "admins can update media" on storage.objects;
create policy "admins can update media"
on storage.objects for update to authenticated
using (bucket_id = 'media' and public.is_admin())
with check (bucket_id = 'media' and public.is_admin());

 drop policy if exists "admins can delete media" on storage.objects;
create policy "admins can delete media"
on storage.objects for delete to authenticated
using (bucket_id = 'media' and public.is_admin());

-- بعد از ساخت کاربر مدیر در Authentication > Users، شناسه UUID او را جایگزین کنید:
-- insert into public.admin_users (id) values ('UUID-USER-HERE');
